server:
  port: 8000
  servlet:
    context-path: /api

constants:
  iva: 0.15
  pagination:
    size: 10

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beagle_bar
    username: root
    password: admin
  application:
    name: Beagle Bar Server
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update